#the main entry for outside world is configured here
apiVersion: v1
kind: Service
metadata:
  name: platformnpservices-srv
spec:
  type: NodePort
  selector:
    app:  platformservice
  ports:
    - name: platformservice
      protocol: TCP
      port: 80  #outside traffic sends request to this port which forwards it to 8080
      targetPort: 8080 